language: scala

scala:
- 2.11.11
- 2.12.4

jdk:
- oraclejdk8

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_8a5c922406f1_key -iv $encrypted_8a5c922406f1_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI

after_success:
- bash <(curl -s https://codecov.io/bash)
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess

notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T024G6JTP'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
